version: "3.9"
services:
  employees:
    build:
      context: ./employees
      dockerfile: ./Dockerfile
    container_name: employees
    ports:
      - 5000:5000
    networks:
      - demo
    restart: always
    volumes:
      - type: bind
        source: ./employees
        target: /usr/src
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    networks:
      - demo
    restart: always
    volumes:
      - type: bind
        source: ./frontend
        target: /usr/src
networks:
  demo:
    driver: bridge
    name: demo
